services:
  mysql:
    image: mysql:8.0
    container_name: ruang_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ruang-kelas-inovatif-db
      MYSQL_USER: ruang-kelas-inovatif-admin
      MYSQL_PASSWORD: mNofgjyjCXAvU00XXX4S
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
