"use client";

import { Button } from "@/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
} from "@/components/ui/dialog";
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { zodResolver } from "@hookform/resolvers/zod";
import { useHookFormOptimisticAction } from "@next-safe-action/adapter-react-hook-form/hooks";
import { Loader2, Pencil } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { getCoursesAction } from "../premium/actions/courses";
import { updateUserAction } from "./user-actions";
import type { PaginatedResult, UserWithProfile } from "./user-types";
import { updateUserSchema } from "./user-validations";

interface UserEditModalProps {
	user: UserWithProfile;
	tableData: PaginatedResult;
	onDataChange: (data: PaginatedResult) => void;
}

export function UserEditModal({
	user,
	tableData,
	onDataChange,
}: UserEditModalProps) {
	const [open, setOpen] = useState(false);
	const [courses, setCourses] = useState<
		Array<{ id: string; courseName: string }>
	>([]);

	// Fetch available courses
	useEffect(() => {
		const fetchCourses = async () => {
			try {
				const result = await getCoursesAction();
				if (result && "data" in result && result.data) {
					setCourses(result.data as Array<{ id: string; courseName: string }>);
				}
			} catch (error) {
				console.error("Error fetching courses:", error);
			}
		};

		if (open) {
			fetchCourses();
		}
	}, [open]);

	const { form, handleSubmitWithAction } = useHookFormOptimisticAction(
		updateUserAction,
		zodResolver(updateUserSchema),
		{
			actionProps: {
				currentState: tableData,
				updateFn: (state, input) => {
					const newData = state.data.map((u) =>
						u.id === input.id
							? {
									...u,
									email: input.email,
									UserProfile: input.profile
										? {
												firstName:
													input.profile.firstName ||
													u.UserProfile?.firstName ||
													"",
												lastName:
													input.profile.lastName ||
													u.UserProfile?.lastName ||
													"",
												phone:
													input.profile.phone || u.UserProfile?.phone || "",
												institution:
													input.profile.institution ||
													u.UserProfile?.institution ||
													"",
												address:
													input.profile.address || u.UserProfile?.address || "",
												city: input.profile.city || u.UserProfile?.city || "",
												province:
													input.profile.province ||
													u.UserProfile?.province ||
													"",
											}
										: u.UserProfile,
									UserCourses: input.courses
										? input.courses.map((courseId) => ({
												id: "", // Will be generated by DB
												courseId,
												course: courses.find((c) => c.id === courseId) || {
													id: courseId,
													courseName: "Unknown",
												},
											}))
										: u.UserCourses,
								}
							: u,
					);
					return {
						...state,
						data: newData,
					};
				},
				onSuccess: (result) => {
					if (result && "data" in result && result.data?.message) {
						toast.success(result.data.message);
						setOpen(false);
						form.reset();
						onDataChange(tableData);
					} else {
						toast.error("Gagal memperbarui user");
					}
				},
				onError: (error) => {
					if (error && typeof error === "object" && "error" in error) {
						const err = error as { error: { serverError?: string } };
						toast.error(err.error?.serverError || "Gagal memperbarui user");
					} else {
						toast.error("Gagal memperbarui user");
					}
				},
			},
			formProps: {
				defaultValues: {
					id: user.id,
					email: user.email,
					profile: user.UserProfile || {
						firstName: "",
						lastName: "",
						phone: "",
						institution: "",
						address: "",
						city: "",
						province: "",
					},
					courses: user.UserCourses?.map((uc) => uc.courseId) || [],
				},
			},
		},
	);

	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogTrigger asChild>
				<Button variant="ghost" size="icon">
					<Pencil className="h-4 w-4" />
				</Button>
			</DialogTrigger>
			<DialogContent className="sm:max-w-[500px] max-h-[90vh] flex flex-col gap-0 p-0">
				<DialogHeader className="px-4 sm:px-6 pt-4 sm:pt-6">
					<DialogTitle>Edit User</DialogTitle>
					<DialogDescription>
						Edit user details using the form below.
					</DialogDescription>
				</DialogHeader>
				<Form {...form}>
					<form
						onSubmit={handleSubmitWithAction}
						className="flex flex-col flex-1 overflow-hidden"
					>
						<div className="flex-1 overflow-y-auto px-4 sm:px-6">
							<div className="space-y-4 pb-4">
								<input type="hidden" {...form.register("id")} />
								<FormField
									control={form.control}
									name="email"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Email</FormLabel>
											<FormControl>
												<Input
													type="email"
													placeholder="Enter email"
													{...field}
													disabled // Email tetap tidak bisa diubah
												/>
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>

								{/* Profile section */}
								<div className="space-y-4">
									<div className="text-sm text-muted-foreground">
										Profile Details
									</div>
									<FormField
										control={form.control}
										name="profile.firstName"
										render={({ field }) => (
											<FormItem>
												<FormLabel>First Name</FormLabel>
												<FormControl>
													<Input placeholder="Enter first name" {...field} />
												</FormControl>
												<FormMessage />
											</FormItem>
										)}
									/>
									<FormField
										control={form.control}
										name="profile.lastName"
										render={({ field }) => (
											<FormItem>
												<FormLabel>Last Name</FormLabel>
												<FormControl>
													<Input placeholder="Enter last name" {...field} />
												</FormControl>
												<FormMessage />
											</FormItem>
										)}
									/>
									<FormField
										control={form.control}
										name="profile.phone"
										render={({ field }) => (
											<FormItem>
												<FormLabel>Phone</FormLabel>
												<FormControl>
													<Input placeholder="Enter phone number" {...field} />
												</FormControl>
												<FormMessage />
											</FormItem>
										)}
									/>
									<FormField
										control={form.control}
										name="profile.institution"
										render={({ field }) => (
											<FormItem>
												<FormLabel>Institution</FormLabel>
												<FormControl>
													<Input placeholder="Enter institution" {...field} />
												</FormControl>
												<FormMessage />
											</FormItem>
										)}
									/>
									<FormField
										control={form.control}
										name="profile.address"
										render={({ field }) => (
											<FormItem>
												<FormLabel>Address</FormLabel>
												<FormControl>
													<Input placeholder="Enter address" {...field} />
												</FormControl>
												<FormMessage />
											</FormItem>
										)}
									/>
									<div className="grid grid-cols-2 gap-4">
										<FormField
											control={form.control}
											name="profile.city"
											render={({ field }) => (
												<FormItem>
													<FormLabel>City</FormLabel>
													<FormControl>
														<Input placeholder="Enter city" {...field} />
													</FormControl>
													<FormMessage />
												</FormItem>
											)}
										/>
										<FormField
											control={form.control}
											name="profile.province"
											render={({ field }) => (
												<FormItem>
													<FormLabel>Province</FormLabel>
													<FormControl>
														<Input placeholder="Enter province" {...field} />
													</FormControl>
													<FormMessage />
												</FormItem>
											)}
										/>
									</div>
								</div>

								{/* Courses section */}
								<FormField
									control={form.control}
									name="courses"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Premium Courses</FormLabel>
											<FormControl>
												<div className="space-y-2">
													<Input 
														type="search"
														placeholder="Search courses..."
														className="mb-2"
														onChange={(e) => {
															const searchTerm = e.target.value.toLowerCase();
															const courseList = document.getElementById('course-list');
															if (courseList) {
																const items = courseList.getElementsByClassName('course-item');
																Array.from(items).forEach((item) => {
																	const text = item.textContent?.toLowerCase() || '';
																	if (text.includes(searchTerm)) {
																		(item as HTMLElement).style.display = '';
																	} else {
																		(item as HTMLElement).style.display = 'none';
																	}
																});
															}
														}}
													/>
													<div 
														id="course-list"
														className="grid grid-cols-1 gap-2 max-h-[200px] overflow-y-auto p-2 border rounded-md"
													>
														{courses.map((course) => (
															<label
																key={course.id}
																className="flex items-center space-x-2 course-item hover:bg-muted/50 p-2 rounded-md"
															>
																<input
																	type="checkbox"
																	checked={field.value?.includes(course.id)}
																	onChange={(e) => {
																		const value = field.value || [];
																		if (e.target.checked) {
																			field.onChange([...value, course.id]);
																		} else {
																			field.onChange(
																				value.filter((id) => id !== course.id),
																			);
																		}
																	}}
																	className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
																/>
																<span className="text-sm">
																	{course.courseName}
																</span>
															</label>
														))}
													</div>
												</div>
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
							</div>
						</div>
						<div className="flex justify-end gap-2 p-4 sm:p-6 border-t bg-muted/50">
							<Button
								type="button"
								variant="outline"
								onClick={() => setOpen(false)}
							>
								Cancel
							</Button>
							<Button type="submit" disabled={form.formState.isSubmitting}>
								{form.formState.isSubmitting ? (
									<>
										<Loader2 className="mr-2 h-4 w-4 animate-spin" />
										Updating...
									</>
								) : (
									"Update"
								)}
							</Button>
						</div>
					</form>
				</Form>
			</DialogContent>
		</Dialog>
	);
}
