"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useHookFormOptimisticAction } from "@next-safe-action/adapter-react-hook-form/hooks";
import { Loader2, Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
} from "@/components/ui/dialog";
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { getCoursesAction } from "../premium/actions/courses";
import { createUserAction } from "./user-actions";
import type { PaginatedResult } from "./user-types";
import { createUserSchema } from "./user-validations";

export function UserAddModal({ users }: { users: PaginatedResult }) {
	const [open, setOpen] = useState(false);
	const [courses, setCourses] = useState<
		Array<{ id: string; courseName: string }>
	>([]);

	// Fetch available courses
	useEffect(() => {
		const fetchCourses = async () => {
			try {
				const result = await getCoursesAction();
				if (result && "data" in result && result.data) {
					setCourses(result.data as Array<{ id: string; courseName: string }>);
				}
			} catch (error) {
				console.error("Error fetching courses:", error);
			}
		};

		if (open) {
			fetchCourses();
		}
	}, [open]);

	const { form, handleSubmitWithAction, resetFormAndAction } =
		useHookFormOptimisticAction(
			createUserAction,
			zodResolver(createUserSchema),
			{
				actionProps: {
					currentState: users,
					updateFn: (state, input) => ({
						...state,
						data: [
							{
								id: Date.now().toString(),
								email: input.email,
								isAdmin: false,
								createdAt: new Date(),
								updatedAt: new Date(),
								UserProfile: {
									...input.profile,
								},
								UserCourses: input.courses
									? input.courses.map((courseId) => ({
											id: "", // Will be generated by DB
											courseId,
											course: courses.find((c) => c.id === courseId) || {
												id: courseId,
												courseName: "Unknown",
											},
										}))
									: [],
							},
							...state.data,
						],
						total: state.total + 1,
						pageCount: Math.ceil((state.total + 1) / 5),
					}),
					onSuccess: (result) => {
						if (result && "data" in result && result.data?.success) {
							setOpen(false);
							toast.success("User created successfully");
							resetFormAndAction();
						} else {
							toast.error(
								typeof result?.data?.error === "string"
									? result.data.error
									: "Failed to create user",
							);
						}
					},
					onError: (error) => {
						toast.error(
							typeof error === "string" ? error : "Failed to create user",
						);
					},
				},
				formProps: {
					defaultValues: {
						email: "",
						password: "",
						profile: {
							firstName: "",
							lastName: "",
							phone: "",
							institution: "",
							address: "",
							city: "",
							province: "",
						},
						courses: [],
					},
				},
			},
		);

	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogTrigger asChild>
				<Button>
					<Plus className="mr-2 h-4 w-4" />
					Add User
				</Button>
			</DialogTrigger>
			<DialogContent className="sm:max-w-[500px] max-h-[90vh] flex flex-col gap-0 p-0">
				<DialogHeader className="px-4 sm:px-6 pt-4 sm:pt-6">
					<DialogTitle>Add New User</DialogTitle>
					<DialogDescription>
						Create a new user by filling out the form below.
					</DialogDescription>
				</DialogHeader>
				<Form {...form}>
					<form
						onSubmit={handleSubmitWithAction}
						className="flex flex-col flex-1 overflow-hidden"
					>
						<div className="flex-1 overflow-y-auto px-4 sm:px-6">
							<div className="space-y-4 pb-4">
								<FormField
									control={form.control}
									name="email"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Email</FormLabel>
											<FormControl>
												<Input
													type="email"
													placeholder="Enter email"
													{...field}
												/>
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="password"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Password</FormLabel>
											<FormControl>
												<Input
													type="password"
													placeholder="Enter password"
													{...field}
												/>
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="profile.firstName"
									render={({ field }) => (
										<FormItem>
											<FormLabel>First Name</FormLabel>
											<FormControl>
												<Input placeholder="Enter first name" {...field} />
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="profile.lastName"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Last Name</FormLabel>
											<FormControl>
												<Input placeholder="Enter last name" {...field} />
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="profile.phone"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Phone</FormLabel>
											<FormControl>
												<Input placeholder="Enter phone number" {...field} />
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="profile.institution"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Institution</FormLabel>
											<FormControl>
												<Input placeholder="Enter institution" {...field} />
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="profile.address"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Address</FormLabel>
											<FormControl>
												<Input placeholder="Enter address" {...field} />
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="profile.city"
									render={({ field }) => (
										<FormItem>
											<FormLabel>City</FormLabel>
											<FormControl>
												<Input placeholder="Enter city" {...field} />
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="profile.province"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Province</FormLabel>
											<FormControl>
												<Input placeholder="Enter province" {...field} />
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
								<FormField
									control={form.control}
									name="courses"
									render={({ field }) => (
										<FormItem>
											<FormLabel>Premium Courses</FormLabel>
											<FormControl>
												<div className="grid grid-cols-1 gap-2 max-h-[200px] overflow-y-auto p-2 border rounded-md">
													{courses.map((course) => (
														<label
															key={course.id}
															className="flex items-center space-x-2"
														>
															<input
																type="checkbox"
																checked={field.value?.includes(course.id)}
																onChange={(e) => {
																	const value = field.value || [];
																	if (e.target.checked) {
																		field.onChange([...value, course.id]);
																	} else {
																		field.onChange(
																			value.filter((id) => id !== course.id),
																		);
																	}
																}}
																className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
															/>
															<span className="text-sm">
																{course.courseName}
															</span>
														</label>
													))}
												</div>
											</FormControl>
											<FormMessage />
										</FormItem>
									)}
								/>
							</div>
						</div>
						<div className="flex justify-end gap-2 p-4 sm:p-6 border-t bg-muted/50">
							<Button
								type="button"
								variant="outline"
								onClick={() => setOpen(false)}
							>
								Cancel
							</Button>
							<Button type="submit" disabled={form.formState.isSubmitting}>
								{form.formState.isSubmitting ? (
									<>
										<Loader2 className="mr-2 h-4 w-4 animate-spin" />
										Creating...
									</>
								) : (
									"Create"
								)}
							</Button>
						</div>
					</form>
				</Form>
			</DialogContent>
		</Dialog>
	);
}
